name: CI

on:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10.0.0
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm --dir=lib install
            - name: Build
              run: pnpm --dir=lib build
            - name: Check format
              run: pnpm --dir=lib check-format
            - name: Check exports
              run: pnpm --dir=lib check-exports
            - name: Lint
              run: pnpm --dir=lib lint
            # node-web-audio-api don't work in CI right now smdh.
            # - name: Test
            #   run: pnpm --dir=lib test
